[package]
name = "denial-app"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
publish = false

[dependencies]
denial-flutter-engine = { path = "../compositor/flutter-engine" }
smithay-client-toolkit = "=0.20.0"
wayland-client = { version = "=0.31.14", features = ["system"] }
wayland-egl = "=0.32.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
zbus = "=5.18.0"
url = "=2.5.8"

[build-dependencies]
gl_generator = "=0.14.0"

[profile.release]
lto = "thin"
strip = "debuginfo"
